### ISSUE TITLE
Checklist improvements

### ISSUE THREAD

**Issue by phadej** [futurice/haskell-mega-repo#259]
- [x] archive / invalid user states
- [x] Edit -> Save -button labels
- [x] info `input` -> `textarea`.
- [x] http://stackoverflow.com/questions/22983013/how-to-get-html-5-input-type-date-working-in-firefox-and-or-ie-10
- [x] first & last name mess in form
- [x] tribe select

**Comment by phadej** [comment]
See #261
